from typing import Any, List, Optional

class Output:
    def print_table(self, table_data: List[List[Any]], title: str = "", columns: Optional[List[str]] = None): ...
    def print_md(self, markdown_str: str): ...
    def close(self): ...

class Logger:
    def info(self, msg: str, *args: Any): ...
    def warning(self, msg: str, *args: Any): ...
    def error(self, msg: str, *args: Any): ...
    def debug(self, msg: str, *args: Any): ...

def get_output() -> Output: ...
def get_logger() -> Logger: ...
