from typing import Generic, Iterable, Iterator, MutableSequence, TypeVar, overload

_T = TypeVar("_T")


class List(MutableSequence[_T], Generic[_T]):
    def __init__(self, iterable: Iterable[_T] = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> _T: ...
    def __setitem__(self, index: int, value: _T) -> None: ...
    def __delitem__(self, index: int) -> None: ...
    def __iter__(self) -> Iterator[_T]: ...
    def insert(self, index: int, value: _T) -> None: ...
    def Add(self, value: _T) -> None: ...
    def Clear(self) -> None: ...

    @property
    def Count(self) -> int: ...
