from typing import Any
from Autodesk.Revit.DB import Document
from Autodesk.Revit.UI import UIDocument
from Autodesk.Revit import DB as DB

doc: Document
uidoc: UIDocument
db: Any = DB

class Transaction:
    def __init__(self, name: str, doc: Document = ...): ...
    def __enter__(self) -> Transaction: ...
    def __exit__(self, exc_type, exc_val, exc_tb): ...

class TransactionGroup:
    def __init__(self, name: str, doc: Document = ...): ...
    def __enter__(self) -> TransactionGroup: ...
    def __exit__(self, exc_type, exc_val, exc_tb): ...
